networks:
  app-network:
    name: network-alexpassalis_com
    driver: bridge

services:
  postgres:
    image: image-postgres
    container_name: container-postgres
    networks:
      - app-network
    restart: always
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -h localhost -U dev_postgres_user -d dev_postgres_db',
        ]
      interval: 10s
      timeout: 10s
      retries: 2
    volumes:
      - ./volumes/postgresql/data:/var/lib/postgresql/data
