volumes:
  postgres:
  redis:

secrets:
  POSTGRES_DB:
    external: true
  POSTGRES_USER:
    external: true
  POSTGRES_PASSWORD:
    external: true
  REDIS_PASSWORD:
    external: true
  POSTGRES_URL:
    external: true
  HONO_BETTER_AUTH_SECRET:
    external: true
  GOOGLE_CLIENT_ID:
    external: true
  GOOGLE_CLIENT_SECRET:
    external: true
  NODEMAILER_AUTH_USER:
    external: true
  NODEMAILER_AUTH_PASS:
    external: true

services:
  dozzle:
    deploy:
      restart_policy:
        condition: any
      update_config:
        order: start-first
        failure_action: rollback
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_NO_ANALYTICS=true
    ports:
      - '8080:8080'
    healthcheck:
      start_period: 30s
      start_interval: 5s
      test: ['CMD', '/dozzle', 'healthcheck']
      interval: 10s
      timeout: 5s
      retries: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  postgres:
    deploy:
      restart_policy:
        condition: any
      update_config:
        order: start-first
        failure_action: rollback
    image: ghcr.io/alexpassalis/image-postgres:latest
    env_file:
      - ./apps/postgres/.env.production
    secrets:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    environment:
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
    healthcheck:
      start_period: 30s
      start_interval: 5s
      test:
        [
          'CMD-SHELL',
          'pg_isready -d $$(cat /run/secrets/POSTGRES_DB) -U $$(cat /run/secrets/POSTGRES_USER)',
        ]
      interval: 10s
      timeout: 5s
      retries: 2
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    deploy:
      restart_policy:
        condition: any
      update_config:
        order: start-first
        failure_action: rollback
    image: redis:7.0-alpine3.17
    volumes:
      - ./apps/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis:/data
    command:
      [
        'redis-server',
        '/usr/local/etc/redis/redis.conf',
        '--save',
        '60',
        '1',
        '--loglevel',
        'notice',
      ]
    secrets:
      - REDIS_PASSWORD
    healthcheck:
      start_period: 30s
      start_interval: 5s
      test:
        [
          'CMD-SHELL',
          'redis-cli -h localhost -p 6379 -a $$(cat /run/secrets/REDIS_PASSWORD) ping | grep PONG || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 2

  hono:
    deploy:
      restart_policy:
        condition: any
      update_config:
        order: start-first
        failure_action: rollback
      mode: replicated
      replicas: 2
    image: ghcr.io/alexpassalis/image-hono:latest
    volumes:
      - ./apps/hono/.env.production:/app/.env.production:ro
    secrets:
      - POSTGRES_URL
      - REDIS_PASSWORD
      - HONO_BETTER_AUTH_SECRET
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - NODEMAILER_AUTH_USER
      - NODEMAILER_AUTH_PASS
    environment:
      HOSTNAME: 0.0.0.0
      PORT: 4000
    healthcheck:
      start_period: 30s
      start_interval: 5s
      test:
        [
          'CMD-SHELL',
          'curl -f http://localhost:4000/api/hono | grep ok || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 2

  nextjs:
    deploy:
      restart_policy:
        condition: any
      update_config:
        order: start-first
        failure_action: rollback
      mode: replicated
      replicas: 2
    image: ghcr.io/alexpassalis/image-nextjs:latest
    volumes:
      - ./apps/nextjs/.env.production:/app/.env.production:ro
    environment:
      HOSTNAME: 0.0.0.0
      PORT: 3000
    healthcheck:
      start_period: 30s
      start_interval: 5s
      test:
        [
          'CMD-SHELL',
          'curl -f http://localhost:3000/api/nextjs | grep ok || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 2

  nginx:
    deploy:
      restart_policy:
        condition: any
      update_config:
        order: start-first
        failure_action: rollback
      mode: replicated
      replicas: 2
    image: nginx:1.27-alpine
    volumes:
      - ./apps/nginx/certs:/etc/nginx/certs:ro
      - ./apps/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '443:443'
    healthcheck:
      start_period: 30s
      start_interval: 5s
      test: ['CMD-SHELL', 'service nginx status || exit 1']
      interval: 10s
      timeout: 5s
      retries: 2
