networks:
  app-network:
    name: network-alexpassalis_com
    driver: bridge

services:
  postgres:
    image: ghcr.io/alexpassalis/image-postgres
    container_name: container-postgres
    networks:
      - app-network
    restart: always
    environment:
      POSTGRES_DB: dev_postgres_db
      POSTGRES_USER: dev_postgres_user
      POSTGRES_PASSWORD: dev_postgres_password
      POSTGRES_HOST: dev-postgres
      POSTGRES_PORT: 5432
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -h localhost -U dev_postgres_user -d dev_postgres_db',
        ]
      interval: 10s
      timeout: 10s
      retries: 2
    volumes:
      - ./volumes/postgresql/data:/var/lib/postgresql/data
