networks:
  app-network:
    name: network-alexpassalis_com
    driver: bridge

services:
  postgres:
    image: image-postgres
    container_name: container-postgres
    networks:
      - app-network
    restart: always
    env_file:
      - ./apps/postgres/.env
    environment:
      - PORT=5432
    volumes:
      - ./../volumes/postgresql/data:/var/lib/postgresql/data

  fastify-1:
    image: image-fastify
    container_name: container-fastify-1
    networks:
      - app-network
    restart: always
    environment:
      - PORT=4001

  next_js-1:
    image: image-next_js
    container_name: container-next_js-1
    networks:
      - app-network
    restart: always
    depends_on:
      - fastify-1
    environment:
      - PORT=3001

  next_js-2:
    image: image-next_js
    container_name: container-next_js-2
    networks:
      - app-network
    restart: always
    depends_on:
      - fastify-1
    environment:
      - PORT=3002

  next_js-3:
    image: image-next_js
    container_name: container-next_js-3
    networks:
      - app-network
    restart: always
    depends_on:
      - fastify-1
    environment:
      - PORT=3003

  nginx:
    image: image-nginx
    container_name: container-nginx
    networks:
      - app-network
    restart: always
    depends_on:
      - fastify-1
      - next_js-1
      - next_js-2
      - next_js-3
    ports:
      - '443:443'
