services:
  postgresql:
    image: postgres:17
    container_name: postgresql
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: exampledb
      PORT: 5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  next-js:
    build:
      context: ./front-end/next-js
      dockerfile: Dockerfile
    container_name: next-js
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgres://example:example@postgresql:5432/exampledb
    depends_on:
      - postgresql

  caddy:
    image: caddy:2.6.4
    container_name: caddy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - next-js

volumes:
  postgresql_data:
  caddy_data:
  caddy_config:
