networks:
  app-network:
    name: network-alexpassalis_com
    driver: bridge

services:
  fastify-1:
    image: image-fastify
    container_name: container-fastify-1
    environment:
      - PORT=4001
    networks:
      - app-network
    restart: always

  next_js-1:
    image: image-next_js
    container_name: container-next_js-1
    environment:
      - PORT=3001
    networks:
      - app-network
    restart: always

  next_js-2:
    image: image-next_js
    container_name: container-next_js-2
    environment:
      - PORT=3002
    networks:
      - app-network
    restart: always

  next_js-3:
    image: image-next_js
    container_name: container-next_js-3
    environment:
      - PORT=3003
    networks:
      - app-network
    restart: always

  nginx:
    image: image-nginx
    container_name: container-nginx
    ports:
      - '443:443'
    networks:
      - app-network
    depends_on:
      - fastify-1
      - next_js-1
      - next_js-2
      - next_js-3
    restart: always
