networks:
  app-network:
    name: network-alexpassalis_com
    driver: bridge

secrets:
  secrets-postgres:
    file: ./apps/postgres/.env.secrets

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: container-dozzle
    networks:
      - app-network
    ports:
      - '127.0.0.1:8080:8080'
    healthcheck:
      start_period: 10s
      start_interval: 3s
      test: ['CMD', '/dozzle', 'healthcheck']
      interval: 10s
      timeout: 5s
      retries: 2
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  postgres:
    depends_on:
      dozzle:
        condition: service_healthy
    image: ghcr.io/alexpassalis/image-postgres:latest
    container_name: container-postgres
    networks:
      - app-network
    env_file:
      - ./apps/postgres/.env.production
    secrets:
      - secrets-postgres
    environment:
      POSTGRES_DB_FILE: /run/secrets/secrets-postgres
      POSTGRES_USER_FILE: /run/secrets/secrets-postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/secrets-postgres
    healthcheck:
      start_period: 10s
      start_interval: 3s
      test:
        [
          'CMD-SHELL',
          'pg_isready -h localhost -U dev_postgres_user -d dev_postgres_db',
        ]
      interval: 10s
      timeout: 5s
      retries: 2
    restart: always
    volumes:
      - ./../volumes/postgresql/data:/var/lib/postgresql/data

  redis:
    depends_on:
      dozzle:
        condition: service_healthy
    image: ghcr.io/alexpassalis/image-redis:latest
    container_name: container-redis
    networks:
      - app-network
    environment:
      REDIS_PASSWORD: dev_redis_password
    healthcheck:
      start_period: 10s
      start_interval: 3s
      test:
        [
          'CMD-SHELL',
          'redis-cli -h localhost -p 6379 -a dev_redis_password ping | grep PONG || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 2
    restart: always
