services:
  postgresql:
    image: postgres:latest
    container_name: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: exampledb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nextjs:
    build:
      context: ./next.js  # Path where your Next.js Dockerfile is located
      dockerfile: Dockerfile
    container_name: nextjs
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3000
      # Make sure this references the correct DB service name:
      DATABASE_URL: postgres://example:example@postgresql:5432/exampledb
    depends_on:
      - postgresql

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - nextjs

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
