services:
  dozzle:
    deploy:
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
    image: amir20/dozzle:latest
    ports:
      - '8080:8080'
    healthcheck:
      start_period: 30s
      start_interval: 5s
      test: ['CMD', '/dozzle', 'healthcheck']
      interval: 10s
      timeout: 5s
      retries: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  postgres:
    deploy:
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
    depends_on:
      - dozzle
    image: ghcr.io/alexpassalis/image-postgres:latest
    env_file:
      - ./apps/postgres/.env.production
    secrets:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    environment:
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
    healthcheck:
      start_period: 30s
      start_interval: 5s
      test:
        [
          'CMD-SHELL',
          'pg_isready -d $$(cat /run/secrets/POSTGRES_DB) -U $$(cat /run/secrets/POSTGRES_USER)',
        ]
      interval: 10s
      timeout: 5s
      retries: 2
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    deploy:
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
    depends_on:
      - dozzle
    image: ghcr.io/alexpassalis/image-redis:latest
    secrets:
      - REDIS_PASSWORD
    healthcheck:
      start_period: 30s
      start_interval: 5s
      test:
        [
          'CMD-SHELL',
          'redis-cli -h localhost -p 6379 -a $$(cat /run/secrets/REDIS_PASSWORD) ping | grep PONG || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 2

volumes:
  postgres:

secrets:
  POSTGRES_DB:
    external: true
  POSTGRES_USER:
    external: true
  POSTGRES_PASSWORD:
    external: true
  REDIS_PASSWORD:
    external: true
