services:
  next-js-1:
    image: next-js-image
    container_name: next-js-1-container
    environment:
      - PORT=3001
    expose:
      - '3001'
    restart: always

  next-js-2:
    image: next-js-image
    container_name: next-js-2-container
    environment:
      - PORT=3002
    expose:
      - '3002'
    restart: always

  next-js-3:
    image: next-js-image
    container_name: next-js-3-container
    environment:
      - PORT=3003
    expose:
      - '3003'
    restart: always

  nginx:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    image: nginx-image
    container_name: nginx-container
    ports:
      - '443:443'
      - '80:80'
    restart: always
    depends_on:
      - next-js-1
      - next-js-2
      - next-js-3
