networks:
  network-alexpassalis_com:
    driver: bridge

services:
  next-js-1:
    image: image-next-js
    container_name: container-next-js-1
    environment:
      - PORT=3001
    networks:
      - network-alexpassalis_com
    restart: always

  next-js-2:
    image: image-next-js
    container_name: container-next-js-2
    environment:
      - PORT=3002
    networks:
      - network-alexpassalis_com
    restart: always

  next-js-3:
    image: image-next-js
    container_name: container-next-js-3
    environment:
      - PORT=3003
    networks:
      - network-alexpassalis_com
    restart: always

  nginx:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    image: image-nginx
    container_name: container-nginx
    ports:
      - '443:443'
    networks:
      - network-alexpassalis_com
    depends_on:
      - next-js-1
      - next-js-2
      - next-js-3
    restart: always
