networks:
  network-tracker:
    external: true

volumes:
  postgres:

secrets:
  TRACKER_POSTGRES_DB:
    external: true
  TRACKER_POSTGRES_USER:
    external: true
  TRACKER_POSTGRES_PASSWORD:
    external: true
  TRACKER_POSTGRES_URL:
    external: true

services:
  dozzle:
    image: amir20/dozzle
    networks:
      - network-tracker
    environment:
      - DOZZLE_NO_ANALYTICS=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - '8080:8080'

  postgres:
    image: image-tracker-postgres
    networks:
      - network-tracker
    secrets:
      - TRACKER_POSTGRES_DB
      - TRACKER_POSTGRES_USER
      - TRACKER_POSTGRES_PASSWORD
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB_FILE: /run/secrets/TRACKER_POSTGRES_DB
      POSTGRES_USER_FILE: /run/secrets/TRACKER_POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/TRACKER_POSTGRES_PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432' ### ONLY IN DEV FOR pgAdmin 4 ###

  pgweb:
    image: sosedoff/pgweb
    networks:
      - network-tracker
    secrets:
      - TRACKER_POSTGRES_URL
    entrypoint: ['/bin/sh']
    command:
      - -c
      - 'pgweb --url "$$(cat /run/secrets/TRACKER_POSTGRES_URL)?sslmode=disable" --bind 0.0.0.0 --listen 8081'
    ports:
      - '8081:8081'

  django:
    image: image-tracker-django
    networks:
      - network-tracker
    secrets:
      - TRACKER_POSTGRES_URL
    volumes:
      - ./services/django:/app
    ports:
      - '8000:8000' ### NEEDS FIXING remove when the nginx container comes in

  nuxt:
    image: image-tracker-nuxt
    networks:
      - network-tracker
    volumes:
      - ./services/nuxt:/app
      - /app/node_modules
    ports:
      - '3000:3000' ### NEEDS FIXING remove when the nginx container comes in
