services:
  # PostgreSQL Database
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: exampledb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Next.js Application
  nextjs:
    build:
      context: ./next.js # Path to your Dockerfile
      dockerfile: Dockerfile
    container_name: next.js
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgres://example:example@db:5432/exampledb
    depends_on:
      - db

  # Caddy Reverse Proxy
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - nextjs

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
