name: Build Docker Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository into GitHub Actions runner (ubuntu VM)
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (build tool)
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert the repository owner name to lowercase
        run: |
          echo "OWNER=$(echo \"${{ github.repository_owner }}\" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and tag image-postgres
        run: |
          IMAGE_NAME="ghcr.io/$OWNER/image-postgres"

          # Build the image and tag it with "latest"
          docker build -t $IMAGE_NAME:latest -f apps/postgres/Dockerfile .

          # Add a timestamp tag for versioning
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TIMESTAMP

      - name: Push image-postgres to GHCR
        run: |
          IMAGE_NAME="ghcr.io/$OWNER/image-postgres"

          # Push both the latest and timestamped images
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$(date +%Y%m%d%H%M%S)
