name: Deploy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_IP: ${{ secrets.VPS_IP }}
      VPS_PASSPHRASE: ${{ secrets.VPS_PASSPHRASE }}
    steps:
      - name: Clone repository into GitHub Actions runner (ubuntu VM)
        uses: actions/checkout@v3

      - name: Copy-Paste docker-compose.yml file from github repository to VPS
        uses: appleboy/scp-action
        with:
          username: ${{ env.VPS_USER }}
          host: ${{ env.VPS_IP }}
          password: ${{ env.VPS_PASSPHRASE }}
          source: './docker-compose.yml'
          target: '/home/${{ env.VPS_USER }}/alexpassalis_com/docker-compose.yml'
