name: Deploy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository into GitHub Actions runner (ubuntu VM)
        uses: actions/checkout@v3

      - name: Copy-Paste docker-compose.yml file from github repository to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          username: ${{ secrets.VPS_USER }}
          host: ${{ secrets.VPS_IP }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          source: './docker-compose.yml'
          target: '/home/${{ secrets.VPS_USER }}/alexpassalis_com/'
